name: test1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-65.0.dev <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  video_player: ^2.7.0
  chewie: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  deferred-components:
    - name: box
      libraries:
        - package:test1/box.dart
        - package:chewie/src/chewie_player.dart
        - package:chewie/src/chewie_progress_colors.dart
        - package:chewie/src/cupertino/cupertino_controls.dart
        - package:chewie/src/material/material_controls.dart
        - package:chewie/src/material/material_desktop_controls.dart
        - package:chewie/src/models/option_item.dart
        - package:chewie/src/models/options_translation.dart
        - package:chewie/src/models/subtitle_model.dart
        - package:chewie/src/notifiers/player_notifier.dart
        - package:chewie/src/player_with_controls.dart
        - package:chewie/src/animated_play_pause.dart
        - package:chewie/src/center_play_button.dart
        - package:chewie/src/cupertino/cupertino_progress_bar.dart
        - package:chewie/src/cupertino/widgets/cupertino_options_dialog.dart
        - package:chewie/src/helpers/utils.dart
        - package:chewie/src/material/material_progress_bar.dart
        - package:chewie/src/material/widgets/options_dialog.dart
        - package:chewie/src/material/widgets/playback_speed_dialog.dart
        - package:chewie/src/helpers/adaptive_controls.dart
        - package:provider/src/change_notifier_provider.dart
        - package:provider/src/consumer.dart
        - package:provider/src/listenable_provider.dart
        - package:provider/src/provider.dart
        - package:chewie/src/progress_bar.dart
        - package:nested/nested.dart
      assets:
        - assets/testVideo.mp4

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
